Repository ucsb-cs156-s22/s22-5pm-happycows, pull requests merged in 2022-06, with the labels that each got.

#37 s22-5pm-4 Added ShowLeaderboard Placeholder Page for admins
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminShowLeaderboardPage.js
  frontend/src/tests/pages/AdminShowLeaderboard.test.js
Labels: s22-5pm-4, 10

#42 s22-5pm-4 Add Degradation Field to Commons Table Entity
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
Labels: s22-5pm-4, TBD Points

#60 s22-5pm-4 - Kevin - Frontend Admin List Commons table add boolean show leaderboard field and make create, edit form have this boolean field also.
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s22-5pm-4, Has-peer-cr :+1:, :+1: Merge Candidate, :hourglass_flowing_sand: Waiting on CI/CD to merge

#55 s22-5pm-3 Added backend functionality to query all UserCommons with specific commonsId
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/UserCommonsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/CurrentUserService.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: s22-5pm-3, Has-peer-cr :+1:

#81 Added SQL Query and backend API route created to get the total number of cows in a common
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-5pm-3, :-1: FIXME-peer-cr-missing, :gear: deploying to QA

#53 s22-5pm-4 Add Generic Error Handling to API Requests
  src/main/java/edu/ucsb/cs156/happiercows/advice/HappierCowsAdvice.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/CoffeeException.java
  src/main/java/edu/ucsb/cs156/happiercows/errors/GenericError.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/errors/GenericErrorTests.java
Labels: s22-5pm-4, 20

#67 s22-5pm-4 Added leaderboard page to storybook
  frontend/src/stories/pages/AdminShowLeaderboardPage.stories.js
Labels: s22-5pm-4, :+1: Merge Candidate, :hourglass_flowing_sand: Waiting on CI/CD to merge

#70 s22-5pm-3 Added backend functionality for Admin to delete UserCommons by userId and commonsId
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: s22-5pm-3, 10

#83 Fixed spam "UserCommons with id X not found" bug
  frontend/src/main/pages/PlayPage.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: s22-5pm-3, Has-peer-cr :+1:, :question: Ready for Staff Review, :gear: deploying to QA

#61 s22-5pm-3 Fixed Announcement Display Bug to Correctly Display Day Number, Ending Date, and Total Players
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: s22-5pm-3, :-1: FIXME-peer-cr-missing

#71 s22-5pm-3 Added Button to Play Page to Route to Leaderboard Page
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsOverview.js
Labels: s22-5pm-3, Has-peer-cr :+1:, :question: Ready for Staff Review

#58 s22-5pm-4 Degradation Rate Field Added to CommonsForm and CommonsTable
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s22-5pm-4, 10

#62 s22-5pm-4 - Hunter - add degradation rate field to backend APIs
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-5pm-4, Has-peer-cr :+1:, :question: Ready for Staff Review
