Repository ucsb-cs156-s22/s22-5pm-happycows, pull requests merged in 2022-05, with the labels that each got.

#14 Heroku QA Deployment Setup
  README.md
Labels: 5PM-3

#8 5pm-3 Updated Links For Docs and Docs-QA in README.md
  README.md
Labels: s22-5pm-3, 5

#15 Adding codecoverage badge for 5pm happycows
  README.md
Labels: s22-5pm-3, 5

#25 Heroku QA Dashboard link to README
  README.md
Labels: SETUP, s22-5pm-3, 5

#40 s22-5pm-3 Pull From Starter to Increase Pitest Coverage
  .env.SAMPLE
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/HappierCowsApplication.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/jobs/Job.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/jobs/JobsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContext.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobContextConsumer.java
  src/main/java/edu/ucsb/cs156/happiercows/services/jobs/JobService.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CSRFControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserTests.java
Labels: s22-5pm-3, Has-peer-cr :+1:

#23 as - add heroku qa app link for 5pm-4
  README.md
Labels: s22-5pm-4, Has-peer-cr :+1:, :question: Ready for Staff Review

#46 s22-5pm-4 nw - added leaderboard bool field
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s22-5pm-4, Has-peer-cr :+1:, :+1: Merge Candidate

#44 s22-5pm-3 Footer Component Github link update
  frontend/src/main/components/Nav/Footer.js
Labels: s22-5pm-3, Has-peer-cr :+1:, :+1: Merge Candidate

#50 s22-5pm-4, Arjun - added more stories to navbar
  frontend/src/stories/components/Nav/AppNavbar.stories.js
Labels: s22-5pm-4

#41 Staff PC: Minor technical corrections to pom.xml, jobs code.
  README.md
  pom.xml
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: s22-staff, :+1: Merge Candidate
